version: "3.7"

services:
  web:
    image: nginx:alpine
    ports:
      - 8083:80
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
  phpfpm:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./tmp/grinds:/tmp/grinds
    networks:
      - www
    environment:
      XDEBUG_CONFIG: client_host=192.168.1.106
      DEBUG: 1
    working_dir: /var/www

  phpdb:
    container_name: phpdb
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: uesr
      MYSQL_PASSWORD: 123456
    ports:
      - "9906:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - www

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    links:
      - phpdb
    environment:
      PMA_HOST: phpdb
    networks:
      - www

networks:
  www:
